name: macOS CI

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  macos-build:
    name: Build on macOS
    strategy:
      matrix:
        python-version: ["3.10"]
        compiler: ["clang"]
        include:
          - compiler: "clang"
            c_compiler: "/usr/local/opt/ccache/libexec/clang"
            cxx_compiler: "/usr/local/opt/ccache/libexec/clang++"
    runs-on: "macos-12"
    env:
      C_COMPILER: ${{ matrix.c_compiler }}
      CXX_COMPILER: ${{ matrix.cxx_compiler }}
      PYTHON: ${{ matrix.python-version }}
      CACHE_NAME: "ccache-qulacs-build-v2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          # Include compiler to distinguish cache for each compiler.
          key: ${{ github.job }}-macos-12-${{ matrix.compiler }}
          verbose: 2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies for macOS
        run: |
          brew upgrade
          brew install boost libomp
          brew link boost

      # - name: Install qulacs for macOS
      #   run: USE_TEST=Yes ./script/build_clang.sh

      - name: Install qulacs Python module
        run: USE_TEST=Yes pip install .[ci] -vvv

      - run: |
          ls -la /Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages

      - name: Test in macOS
        run: |
          cd ./build
          make test -j
          make pythontest -j
