name: macOS CI

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  macos-cpp-test:
    name: C++ Test on macOS
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc", "clang"]
        include:
          - compiler: "gcc"
            c_compiler: "gcc-11"
            cxx_compiler: "g++-11"
          - compiler: "clang"
            c_compiler: "clang"
            cxx_compiler: "clang++"
    runs-on: "macos-12"
    env:
      C_COMPILER: ${{ matrix.c_compiler }}
      CXX_COMPILER: ${{ matrix.cxx_compiler }}
      USE_TEST: "Yes"
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          # Include compiler to distinguish cache for each compiler.
          key: ${{ github.job }}-macos-12-${{ matrix.compiler }}
          verbose: 2

      - name: Install dependencies for macOS
        run: |
          brew install boost libomp
          brew link boost

      - name: Build qulacs for macOS
        run: ./script/build_gcc.sh

      - name: Test in macOS
        run: |
          cd ./build
          make test -j

  macos-python-test:
    name: Python Test on macOS
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        compiler: ["gcc", "clang"]
        include:
          - compiler: "gcc"
            c_compiler: "gcc-11"
            cxx_compiler: "g++-11"
          - compiler: "clang"
            c_compiler: "clang"
            cxx_compiler: "clang++"
    runs-on: "macos-12"
    env:
      C_COMPILER: ${{ matrix.c_compiler }}
      CXX_COMPILER: ${{ matrix.cxx_compiler }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          # Include compiler to distinguish cache for each compiler.
          key: ${{ github.job }}-macos-12-${{ matrix.compiler }}
          verbose: 2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies for macOS
        run: |
          brew install boost libomp
          brew link boost

      - name: Install qulacs Python module
        run: pip install .[ci] -vvv

      - name: Test in macOS
        run: |
          cd ./build
          make pythontest -j
